spring:
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  # Step 1a: Configure SSL with the certificate and private key
  # ...
  # Step 1a: End of SSL configuration


  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZzNOSW5SNnltVVRxOUNKOGUKSkI1eU5zektSZm1LQ0NkTmQvTUpDaHFWZXB1aFJBTkNBQVFoZ3QyV0Z1MU1ST3VReUgxZ0FON0VDMlIyLzF3OAp3VllzRFRHSDFsTzBGNFRlb1lqandkSEhoQi9mcjVXMzI5YXNIZGJ1R2RKNGY3WUJmVW1RNURBVAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURUVENDQWJXZ0F3SUJBZ0lRRHBqaGhWdW4vQnhpS09WZllhZDBxREFOQmdrcWhraUc5dzBCQVFzRkFEQmoKTVI0d0hBWURWUVFLRXhWdGEyTmxjblFnWkdWMlpXeHZjRzFsYm5RZ1EwRXhIREFhQmdOVkJBc01FMjFoYlhOQQpiV0Z0Y3lBb1RXRnRZV1J2ZFNreEl6QWhCZ05WQkFNTUdtMXJZMlZ5ZENCdFlXMXpRRzFoYlhNZ0tFMWhiV0ZrCmIzVXBNQjRYRFRJMk1EUXhOVEV6TURNd09Gb1hEVEk0TURjeE5URXpNRE13T0Zvd1J6RW5NQ1VHQTFVRUNoTWUKYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUdObGNuUnBabWxqWVhSbE1Sd3dHZ1lEVlFRTERCTnRZVzF6UUcxaApiWE1nS0UxaGJXRmtiM1VwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFSVlMZGxoYnRURVRyCmtNaDlZQURleEF0a2R2OWNQTUZXTEEweGg5WlR0QmVFM3FHSTQ4SFJ4NFFmMzYrVnQ5dldyQjNXN2huU2VIKzIKQVgxSmtPUXdFNk5rTUdJd0RnWURWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQgpNQjhHQTFVZEl3UVlNQmFBRkpWZ3R2ZGxmT1cyL2U1SDlHRXVJYVhLRVd2TU1Cb0dBMVVkRVFRVE1CR0NEMnh2ClkyRnNMakI0WkdKbExtUmxkakFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBT0tMVDRWYnBrUGNoZ0hudWpZcGgKWDN5TlozcHlCSnNjUlV6SUxud0dZWFZXSzhLdW1xdEJIM3VOSFVIWWVXU1orcXMxajBMWXZTNFJxWWc4alFqcwpIUnkzWFJQekRLSi9rbkdoVjk5dVNDWHpzbnhBS1VxRlliZ1VZS0lHK1RjUWxRalhicW5EbDE0K1orY0FLYnlHCllJcjFSRE5hNHIxemNZc3lBN21zLzh0TjdCL0tRVEh0Y01COGVaOEh3MUwzTUdvK3BIOHdHc1FCSWVBZXkwS2gKeUxuN2Q5UjhYRFZEUTNTZDVxeFVSQVZUZ3QrVWtia0dwQVRKWGpRWXR5UW9QaG9zUUJXTmtIeHJsejZ4eTF1cgpDUnFGS040ZEI1aHh0Rzlld0lYQVMyZHVZL3dFUTEzWjNsaDNBN3JlblV6Zm1CL29pUFZBRkdqajlsdGlUMHp3Ck5QKzY5aUN2ZC9DR3ZUNWMxMm0vMEYxNWFKZEdEakRZT1lHbVMyWXhtaVZWLzNrZUhuR0NDZXRaWWRjYlE2OEkKY3JvYXdmZUhQUFhFemphTmF3WGxXTnp2cXozSDg2WmFIcXhCRUV2OUtIYlFkRUpXYmNkRW03dk1Cc2YrWmprLwpLdEZwNzJBRWF5WXQvbjlKTnNlZDZMYks3Q0lwSXZaKzJad2ErbHo5cndDMQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
          truststore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVsVENDQXYyZ0F3SUJBZ0lRZlNXdmh0aFFCQTdXdVpoSVZjZnV4ekFOQmdrcWhraUc5dzBCQVFzRkFEQmoKTVI0d0hBWURWUVFLRXhWdGEyTmxjblFnWkdWMlpXeHZjRzFsYm5RZ1EwRXhIREFhQmdOVkJBc01FMjFoYlhOQQpiV0Z0Y3lBb1RXRnRZV1J2ZFNreEl6QWhCZ05WQkFNTUdtMXJZMlZ5ZENCdFlXMXpRRzFoYlhNZ0tFMWhiV0ZrCmIzVXBNQjRYRFRJMk1EUXhOVEV5TlRVME1Gb1hEVE0yTURReE5URXlOVFUwTUZvd1l6RWVNQndHQTFVRUNoTVYKYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1Sd3dHZ1lEVlFRTERCTnRZVzF6UUcxaGJYTWdLRTFoYldGawpiM1VwTVNNd0lRWURWUVFEREJwdGEyTmxjblFnYldGdGMwQnRZVzF6SUNoTllXMWhaRzkxS1RDQ0FhSXdEUVlKCktvWklodmNOQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQU1FV3NVclhaQmtMTGVvL0dQNEFrVHpGSkRXRGhHSlAKeS8yMXdzckN6T0NUUDNodEdBc1A0MkR0Q3d3bndVdWI2LzV1UGN2cW5La3BzTmdCalhqSGxmbGNET0dIL2l5awpRUjduRGhnNnNYRWtXZ3JyQ24vUTk3bDhxZmlab09uL2MvaC91QVh2TndTVTlJYWtRRkdoRC8wdTB6TmxFS1ZsCm5oUkVrR3RTTDFXM0VYckp2cVI4RTZRMmtiWlZNc1BKRmdnbEZYd0dNR2lrWjBWaktpWTZBa1NjNnJHWm5Pa0cKeDQ4WVhiVnRTeVQ4OWNkdldvNWM0OERUSFJaN0VDd1VoSllBM3p0Q2FGaURXdG93dXltdDJtUVJ4ZXlqN1BtQgpnU3BFcm9WZmVaTFVPL3c1bzlVZUZyNUNpSjVpemZUUkRoQnJDTmd3dXFPc3lsWXF3dkgwT0t3OWVzMTJ6SjJYCnVPcUs5bVRMdmE0VEowajZDQWRYZU9Lc0NjVFZLVUg1VXQ5UFlvdVNQQ2hXY0Noc0tyVXQrMFFFQjcvZzcxbTMKcFpBZ3AzTjlkVlhtWDZJaUJWZDVCUURycFBqMisxNm9pZDZSc1FWdHZQNXBxcXdzR3dNaTN4UDgwVEhrdk9pTwpYSlEwUzV4MUd6SlZBdHVIREQzSVYxQVRRaEdXWXo1ZEdRSURBUUFCbzBVd1F6QU9CZ05WSFE4QkFmOEVCQU1DCkFnUXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBREFkQmdOVkhRNEVGZ1FVbFdDMjkyVjg1YmI5N2tmMFlTNGgKcGNvUmE4d3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnR0JBR1A1ZXZTVzcwODlxRGZJSkZvM29jdUFkUlZsZ0s0YwpTM2poWk16ZUZBd2FpTmhUWkhyWGI3R2hkSW5LdmIrcG4zTTB4MWwybmJ5OE9TS1JYZThkNURFL3ZSTUdCc2Q1CklEQjhDUUp2alZabjlHemhkdTAxRkZnMTlGOUp3elh3RlBTV2FqQnBkcG50UVhvOU1HNW9sdS9tUkdzR3FoTUMKbWpjS1VmRDJzTEh2RGZBVUFNdDltajVlbkU5MTZUcVNZUm5aVEcxQlBvVFFveXVxTkhhTFp1L24zVTFEckpNSwp4VHhDaXlyOCtiQVRDZlZpWmU4UG5IamdYTHBaejhxOGFVWDZmZG43L3ZtY0V0NkkwM3ZpRG5oTGliVURmSFVUCmhraVk2Ym8vekxJVjFUdWZldkFnMTNHVmdyVGIzWjRQT3hoOXZRTlNmdW5ZcVZPQ3RyWlVKUWUyTFlIa0tVbHMKVzJVdUc1MDFHYW1mTm9uaEZiYVRBc2kwRjIrZ25jMGFueXF3bXpaNUg1LzVMNlRHeXZld1ZiSGFoWVpzR1Z0MQpIUnBMbDZqUXMwUmROMmo3VzdtYTUrMUt4bUJtSk5DU0YyY0JmUE9IL0duekZxbXNpZGRFaW9LUmsvWWZ3dHRYCnRoUllJYlFWTzFMTW9NeUVIR3BvOWxUYlJYYmFOZ1R1Umc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="

server:
  port: 8443
  # Step 1b: Enable SSL and specify ssl bundle
  # ...
  ssl:
    bundle: web
  # Step 1b: End of SSL configuration
  # Step 5: Configure session cookie with SameSite attribute
  servlet:
    session:
      cookie:
        same-site: strict
  # Step 5: End of session cookie configuration