name: security

on:
  workflow_dispatch

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  osv-scan:
    name: Run OSV Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
    
      - name: Run osv-scanner
        uses: google/osv-scanner-action/osv-scanner-action@7222d1c7ee4f96d71d883e0d3c603f1e1705eca9
        with:
          scan-args: |-
            --format sarif
            --output DependenciesAnalysisFull.sarif
            ./
        continue-on-error: true

      - name: Send report to security dashboard
        uses: github/codeql-action/upload-sarif@v4

  semgrep:
    name: SCA
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep@sha256:326e5f41cc972bb423b764a14febbb62bbad29ee1c01820805d077dd868fea48

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config .semgrep/ \
            --sarif \
            --output semgrep.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        
      
