name: security

on:
  workflow_dispatch

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  osv-scan:
    name: Run OSV Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Run osv-scanner
        uses: google/osv-scanner-action/osv-scanner-action@v1
        with:
          scan-args: |-
            --format sarif
            --output DependenciesAnalysisFull.sarif
            ./
        continue-on-error: true

      - name: Send report to security dashboard
        uses: github/codeql-action/upload-sarif@v3

  semgrep:
    name: SCA
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep@sha256:aba64aaf601ff71b769b082d3c9f95cb02a2bb20a6404f42ae94f240aec6ace7

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config .semgrep/ \
            --sarif \
            --output semgrep.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        
      
